plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
collections:
  authors:
    output: true
  writing:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: writing
    values:
      layout: "writing"
  - scope:
      path: ""
    values:
      layout: "default"
  